backend:
  name: github
  repo: guayoscey-bot/ceysport
  branch: main
  auth_type: pkce
  app_id: 'Ov231iIujfecDzGLsNRE'
  commit_messages:
    create: "Crear producto {{slug}}"
    update: "Actualizar producto {{slug}}"
    delete: "Eliminar producto {{slug}}"

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    format: "json"
    identifier_field: "nombre"
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Producto", name: "nombre", widget: "string"}
      - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
      - {label: "Imagen del Guayo / Producto", name: "imagen", widget: "image"}
      - {label: "Tallas Disponibles", name: "tallas", widget: "string", hint: "Ejemplo: 38, 39, 40, 41"}
      - {label: "Descripción", name: "descripcion", widget: "text", required: false}
